const natures = {
    "hardy": { "increases":"-", "lowers":"-", "likes":"-", "dislikes":"-"},
    "lonely": { "increases":"attack", "lowers":"defense", "likes":"spicy", "dislikes":"sour"},
    "brave": { "increases":"attack", "lowers":"speed", "likes":"spicy", "dislikes":"sweet"},
    "adamant": { "increases":"attack", "lowers":"special-attack", "likes":"spicy", "dislikes":"dry"},
    "naughty": { "increases":"attack", "lowers":"special-defense", "likes":"spicy", "dislikes":"bitter"},
    "docile": { "increases":"-", "lowers":"-", "likes":"-", "dislikes":"-"},
    "bold": { "increases":"defense", "lowers":"attack", "likes":"sour", "dislikes":"spicy"},
    "relaxed": { "increases":"defense", "lowers":"speed", "likes":"sour", "dislikes":"sweet"},
    "impish": { "increases":"defense", "lowers":"special-attack", "likes":"sour", "dislikes":"dry"},
    "lax": { "increases":"defense", "lowers":"special-defense", "likes":"sour", "dislikes":"bitter"},
    "serious": { "increases":"-", "lowers":"-", "likes":"-", "dislikes":"-"},
    "timid": { "increases":"speed", "lowers":"attack", "likes":"sweet", "dislikes":"spicy"},
    "hasty": { "increases":"speed", "lowers":"defense", "likes":"sweet", "dislikes":"sour"},
    "jolly": { "increases":"speed", "lowers":"special-attack", "likes":"sweet", "dislikes":"dry"},
    "naive": { "increases":"speed", "lowers":"special-defense", "likes":"sweet", "dislikes":"bitter"},
    "bashful": { "increases":"-", "lowers":"-", "likes":"-", "dislikes":"-"},
    "modest": { "increases":"special-attack", "lowers":"attack", "likes":"dry", "dislikes":"spicy"},
    "mild": { "increases":"special-attack", "lowers":"defense", "likes":"dry", "dislikes":"sour"},
    "quiet": { "increases":"special-attack", "lowers":"speed", "likes":"dry", "dislikes":"sweet"},
    "rash": { "increases":"special-attack", "lowers":"special-defense", "likes":"dry", "dislikes":"bitter"},
    "quirky": { "increases":"-", "lowers":"-", "likes":"-", "dislikes":"-"},
    "calm": { "increases":"special-defense", "lowers":"attack", "likes":"bitter", "dislikes":"spicy"},
    "gentle": { "increases":"special-defense", "lowers":"defense", "likes":"bitter", "dislikes":"sour"},
    "sassy": { "increases":"special-defense", "lowers":"speed", "likes":"bitter", "dislikes":"sweet"},
    "careful": { "increases":"special-defense", "lowers":"special-attack", "likes":"bitter", "dislikes":"dry"},
}

export default natures;